name = "ai-image-bg-api"
main = "worker.js"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "ai-image-background-users"
database_id = "60ed1a7a-9521-437c-b873-02b7022e7ef0"

[vars]
PAYPAL_MODE = "sandbox"
